create table bus (
   bus_id integer generated by default as identity,
   upd_at timestamp(6),
   upd_by varchar(255),
   last_serviced date,
   make_year integer,
   maker varchar(255),
   registration varchar(255),
   seats integer,
   primary key (bus_id)
);

create table customer (
    customer_id integer generated by default as identity,
    upd_at timestamp(6),
    upd_by varchar(255),
    address varchar(255),
    admin integer,
    city varchar(255),
    email varchar(255),
    first_name varchar(255),
    last_name varchar(255),
    password varchar(255),
    phone varchar(255),
    postcode varchar(255),
    state varchar(255),
    primary key (customer_id)
);

create table travel (
    travel_id integer generated by default as identity,
    upd_at timestamp(6),
    upd_by varchar(255),
    departure_datetime timestamp(6),
    destination varchar(255),
    source varchar(255),
    status varchar(255),
    bus_id integer,
    primary key (travel_id)
);

create table travel_booking (
    travel_booking_id integer generated by default as identity,
    upd_at timestamp(6),
    upd_by varchar(255),
    booked_seats integer,
    booking_datetime timestamp(6),
    customer_id integer,
    travel_id integer,
    primary key (travel_booking_id)
);

alter table if exists travel
add constraint FKtravbus
foreign key (bus_id)
references bus;

alter table if exists travel_booking
add constraint FKtravcust
foreign key (customer_id)
references customer;

alter table if exists travel_booking
add constraint FKtravbook
foreign key (travel_id)
references travel;


